node {
    stage('Checkout') {
        checkout scm
    }
    
    docker.image('maven:3.9.9').inside {
        stage('Build') {
            sh 'mvn -B -DskipTests clean package'
        }
        
        stage('Test') {
            try {
                sh 'mvn test'
            } finally {
                junit 'target/surefire-reports/*.xml'
            }
        }
    }
    
    stage('Manual Approval') {
        input message: 'Lanjutkan ke tahap Deploy?', ok: 'Proceed'
    }
    
    stage('Deploy') {
        sshagent(['ec2-ssh-key']) {
            def jarFile = sh(script: 'ls target/*.jar', returnStdout: true).trim()
            
            sh """
                scp -o StrictHostKeyChecking=no ${jarFile} ubuntu@13.211.87.243:/home/ubuntu/simple-maven-java-app/app.jar
                scp -o StrictHostKeyChecking=no Dockerfile ubuntu@13.211.87.243:/home/ubuntu/simple-maven-java-app/Dockerfile
            """
            
            sh '''
                ssh -o StrictHostKeyChecking=no ubuntu@13.211.87.243 "
                    cd /home/ubuntu/simple-maven-java-app
                    docker stop java-app || true
                    docker rm java-app || true
                    docker build -t java-app .
                    docker run -d --name java-app -p 8080:8080 java-app
                "
            '''
            
            echo 'Aplikasi sedang berjalan. Tunggu 1 menit sebelum dimatikan...'
            sleep(time: 60, unit: 'SECONDS')
            
            sh 'ssh -o StrictHostKeyChecking=no ubuntu@13.211.87.243 "docker stop java-app && docker rm java-app"'
            
            echo 'Aplikasi berhasil dimatikan'
        }
    }
}
