node {
    stage('Checkout') {
        checkout scm
    }
    
    docker.image('maven:3.9.9').inside('-p 8080:8080 -e MAVEN_OPTS="-Dspring.profiles.active=default"') {
        stage('Build') {
            sh 'mvn -B -DskipTests clean package'
        }
        
        stage('Test') {
            try {
                sh 'mvn test'
            } finally {
                junit 'target/surefire-reports/*.xml'
            }
        }
        
        stage('Manual Approval') {
            input message: 'Lanjutkan ke tahap Deploy?', ok: 'Proceed'
        }
        
        stage('Deploy') {
            sshagent(['ec2-ssh-key']) {
                def jarFile = sh(script: 'ls target/*.jar', returnStdout: true).trim()
                
                sh "scp -o StrictHostKeyChecking=no ${jarFile} ubuntu@3.25.53.27:/home/ubuntu/app.jar"
                
                sh '''
                    ssh -o StrictHostKeyChecking=no ubuntu@3.25.53.27 "
                        pkill -f app.jar || true
                        nohup java -jar /home/ubuntu/app.jar > app.log 2>&1 &
                    "
                '''
                
                echo 'Aplikasi sedang berjalan. Tunggu 1 menit sebelum dimatikan...'
                sleep(time: 60, unit: 'SECONDS')
                
                sh 'ssh -o StrictHostKeyChecking=no ubuntu@3.25.53.27 "pkill -f app.jar || true"'
                
                echo 'Aplikasi berhasil dimatikan'
            }
        }
    }
}
