node {
    stage('Checkout') {
        checkout scm
    }
    
    docker.image('maven:3.9.9').inside ('-p 8080:8080'){
        stage('Build') {
            sh 'mvn -B -DskipTests clean package'
        }
        
        stage('Test') {
            try {
                sh 'mvn test'
            } finally {
                junit 'target/surefire-reports/*.xml'
            }
        }
        
        stage('Deliver') {
            sh './jenkins/scripts/deliver.sh'
        }
    }
}
